const studentsDatabase = [// Kelas XI-1
      { nis: "8269", name: "AHMAD NURIL QOLBI", absen: 1, kelas: "XI-1" },
      { nis: "8270", name: "AHMAD RIJAL AL AFIF", absen: 2, kelas: "XI-1" },
      { nis: "8271", name: "AISYAH OCTAVIA AULIA", absen: 3, kelas: "XI-1" },
      { nis: "8276", name: "ALDINO PUTRA ADI NUGRAHA", absen: 4, kelas: "XI-1" },
      { nis: "8283", name: "ALMAGHVIRA RIZKY EFFENDY", absen: 5, kelas: "XI-1" },
      { nis: "8286", name: "ALYSIA DELLA MURFAHANIK FAIZ", absen: 6, kelas: "XI-1" },
      { nis: "8299", name: "AQILAH ATHALLAZAHRA ARDINE", absen: 7, kelas: "XI-1" },
      { nis: "8305", name: "ATHAILLAH AILSA JACINDA", absen: 8, kelas: "XI-1" },
      { nis: "8309", name: "AURA WULAN RAHMADANI", absen: 9, kelas: "XI-1" },
      { nis: "8323", name: "CADEREYN ARETA", absen: 10, kelas: "XI-1" },
      { nis: "8353", name: "ELISABETH SELLYNA", absen: 11, kelas: "XI-1" },
      { nis: "8360", name: "FAISHAL ALI REZA", absen: 12, kelas: "XI-1" },
      { nis: "8363", name: "FAREL ARDINATA MISLANDA PUTRA", absen: 13, kelas: "XI-1" },
      { nis: "8368", name: "FEYOLA VALENCIA UTOMO", absen: 14, kelas: "XI-1" },
      { nis: "8570", name: "IBRANI CALFIN MARBUN", absen: 15, kelas: "XI-1" },
      { nis: "8383", name: "JASMINE PUTRI ALMEERA", absen: 16, kelas: "XI-1" },
      { nis: "8389", name: "KAISYA MUAMMAR", absen: 17, kelas: "XI-1" },
      { nis: "8400", name: "LAILATUL MAGHFIROH HAYATI", absen: 18, kelas: "XI-1" },
      { nis: "8405", name: "LUNA ALMAURA", absen: 19, kelas: "XI-1" },
      { nis: "8413", name: "MALVINO CHOLVI JOVANTAMA", absen: 20, kelas: "XI-1" },
      { nis: "8414", name: "MANITA ARDHIANSYAH RAHMA", absen: 21, kelas: "XI-1" },
      { nis: "8415", name: "MARIA VIDYA KHANDIS", absen: 22, kelas: "XI-1" },
      { nis: "8416", name: "MARINDA AISYAH MAWLAAYA IRBAH", absen: 23, kelas: "XI-1" },
      { nis: "8421", name: "MEISYA NURUL ISNAINI", absen: 24, kelas: "XI-1" },
      { nis: "8431", name: "MOCHAMMAD RAJWA SURYA SASTRO SAPUTRA", absen: 25, kelas: "XI-1" },
      { nis: "8442", name: "MUHAMMAD ASHRAF PUTRA RAHMANI", absen: 26, kelas: "XI-1" },
      { nis: "8572", name: "MUHAMMAD MUJIB HABIBI", absen: 27, kelas: "XI-1" },
      { nis: "8460", name: "MUHAMMAD SULTON ARIF MAULANA", absen: 28, kelas: "XI-1" },
      { nis: "8469", name: "NADIN MAYSAM", absen: 29, kelas: "XI-1" },
      { nis: "8498", name: "PUTRI KUMALASARI", absen: 30, kelas: "XI-1" },
      { nis: "8499", name: "PUTRINADIAN ANDINISARI PURNAMA", absen: 31, kelas: "XI-1" },
      { nis: "8500", name: "QAIDA MAHESWARI ANINDYA HIDAYAT", absen: 32, kelas: "XI-1" },
      { nis: "8506", name: "RAHMANIA AHMAD SAFIRADEWI", absen: 33, kelas: "XI-1" },
      { nis: "8528", name: "SAFIRA ELINA PUTRI", absen: 34, kelas: "XI-1" },
      { nis: "8532", name: "SAMARA PUTRI ZULKIFLI", absen: 35, kelas: "XI-1" },
      { nis: "8556", name: "YASMIN AYU FAIRUNIZA", absen: 36, kelas: "XI-1" },
      
      // Kelas XI-2
      { nis: "8263", name: "ADINDA PUSPITA KARUNIASARI", absen: 1, kelas: "XI-2" },
      { nis: "8265", name: "AFDIAN RASYA NAUFAL", absen: 2, kelas: "XI-2" },
      { nis: "8272", name: "AISYAH SINTA DEWI SYAFITRI", absen: 3, kelas: "XI-2" },
      { nis: "8280", name: "ALFI AULYA SUA AGUSTIN", absen: 4, kelas: "XI-2" },
      { nis: "8303", name: "ARLYNE ANINDYA ANDIK", absen: 5, kelas: "XI-2" },
      { nis: "8310", name: "AURELIA CALLISTA ANGGRAINI", absen: 6, kelas: "XI-2" },
      { nis: "8316", name: "BAGAS PRAWIRA BIMANTARA", absen: 7, kelas: "XI-2" },
      { nis: "8331", name: "CINTYA ALIN PRAMUDITA", absen: 8, kelas: "XI-2" },
      { nis: "8336", name: "DAVIDA DWI PRATIWI", absen: 9, kelas: "XI-2" },
      { nis: "8340", name: "DESFITA CAHYA ARINI", absen: 10, kelas: "XI-2" },
      { nis: "8345", name: "DIO RASYA ADITYA", absen: 11, kelas: "XI-2" },
      { nis: "8357", name: "FAHMIDA HAPSARI RAZZAQEE", absen: 12, kelas: "XI-2" },
      { nis: "8376", name: "HAFIZH ABBAS KURNIAWAN", absen: 13, kelas: "XI-2" },
      { nis: "8377", name: "HARDHIKA YUDHA KAVIN PRATAMA", absen: 14, kelas: "XI-2" },
      { nis: "8382", name: "IZKA LAILA KHOMSA NISA'UL ARIFI", absen: 15, kelas: "XI-2" },
      { nis: "8390", name: "KAMILA NAJA", absen: 16, kelas: "XI-2" },
      { nis: "8394", name: "KEZIA NATALIE WIBOWO", absen: 17, kelas: "XI-2" },
      { nis: "8397", name: "KHOFI ZAKIYYAN ATHO'ULLOH", absen: 18, kelas: "XI-2" },
      { nis: "8399", name: "LAILA ARTA DEWI", absen: 19, kelas: "XI-2" },
      { nis: "8403", name: "LELI AVRILIA", absen: 20, kelas: "XI-2" },
      { nis: "8422", name: "MEY NENSY ZALIATY", absen: 21, kelas: "XI-2" },
      { nis: "8430", name: "MOCHAMMAD MARVIN LUCKIANSYAH WARDANY", absen: 22, kelas: "XI-2" },
      { nis: "8440", name: "MUHAMMAD ALFIN DWI FIRMANSYAH", absen: 23, kelas: "XI-2" },
      { nis: "8449", name: "MUHAMMAD HAIKAL HAMZAH", absen: 24, kelas: "XI-2" },
      { nis: "8459", name: "MUHAMMAD SEPTIAN FALAH RAMADHAN", absen: 25, kelas: "XI-2" },
      { nis: "8474", name: "NASWA LAILY QUTROTUL AINI", absen: 26, kelas: "XI-2" },
      { nis: "8475", name: "NATHANIELA RAIHANAH SETYAWAN", absen: 27, kelas: "XI-2" },
      { nis: "8578", name: "NAURAH YUDITA RAMADHANTI WIBOWO", absen: 28, kelas: "XI-2" },
      { nis: "8479", name: "NAYLA RASYA MAHIRA", absen: 29, kelas: "XI-2" },
      { nis: "8490", name: "NUR AINI", absen: 30, kelas: "XI-2" },
      { nis: "8491", name: "NUR FADILAH", absen: 31, kelas: "XI-2" },
      { nis: "8523", name: "RIZAL AZAM MUZAKI", absen: 32, kelas: "XI-2" },
      { nis: "8538", name: "SYABILA AULIA AZ-ZAHRA", absen: 33, kelas: "XI-2" },
      { nis: "8540", name: "SYIFA FAUZIYAH", absen: 34, kelas: "XI-2" },
      { nis: "8542", name: "TAZKIA VELITA ISTIQFARA", absen: 35, kelas: "XI-2" },
      { nis: "8561", name: "ZAHRATU SYIFA'", absen: 36, kelas: "XI-2" },
      
      // Kelas XI-3
      { nis: "8255", name: "ABIFAEYZA MUHAMMAD DYAURRAHMAN", absen: 1, kelas: "XI-3" },
      { nis: "8257", name: "ABIYYU NAUFAL ZAKY ASNAR", absen: 2, kelas: "XI-3" },
      { nis: "8273", name: "AISYAH ZAHIRA", absen: 3, kelas: "XI-3" },
      { nis: "8566", name: "ALDO VANTINALDO", absen: 4, kelas: "XI-3" },
      { nis: "8290", name: "ANANTA PRATAMA", absen: 5, kelas: "XI-3" },
      { nis: "8296", name: "ANISAH PRATIWI", absen: 6, kelas: "XI-3" },
      { nis: "8315", name: "BACHRALFRIDHO REYSHADIN ILMAN", absen: 7, kelas: "XI-3" },
      { nis: "8317", name: "BENI RAIHAN ADRIANSYAH", absen: 8, kelas: "XI-3" },
      { nis: "8338", name: "DEA KAHAYA AISHAWA", absen: 9, kelas: "XI-3" },
      { nis: "8346", name: "DIRGAHAYU RISKA RAMADANI", absen: 10, kelas: "XI-3" },
      { nis: "8365", name: "FAWWAZKA FALAJ WAHANDY", absen: 11, kelas: "XI-3" },
      { nis: "8374", name: "GALUH AVRIL DINDA ZASKIA", absen: 12, kelas: "XI-3" },
      { nis: "8387", name: "JOSEPH KENZIE SURYA WIJAYA", absen: 13, kelas: "XI-3" },
      { nis: "8404", name: "LIVINA MARIA ASHRAEL", absen: 14, kelas: "XI-3" },
      { nis: "8406", name: "M. AHNAF RAMADHANI", absen: 15, kelas: "XI-3" },
      { nis: "8433", name: "MOHAMMAD ADAM RAYLIANSYAH", absen: 16, kelas: "XI-3" },
      { nis: "8439", name: "MUHAMMAD ALDO RIZQIANSYAH", absen: 17, kelas: "XI-3" },
      { nis: "8450", name: "MUHAMMAD HENDRIK.A.P", absen: 18, kelas: "XI-3" },
      { nis: "8571", name: "MUHAMMAD IZZULIL HAQ", absen: 19, kelas: "XI-3" },
      { nis: "8458", name: "MUHAMMAD SATRIA MAULANA", absen: 20, kelas: "XI-3" },
      { nis: "8461", name: "MUHAMMAD SYAUQIL JINAN", absen: 21, kelas: "XI-3" },
      { nis: "8462", name: "MUHAMMAD WAHYU AL AKBAR", absen: 22, kelas: "XI-3" },
      { nis: "8464", name: "MUKHAMMAD RIZQI YAHYA", absen: 23, kelas: "XI-3" },
      { nis: "8476", name: "NAVISYA AURA MADA", absen: 24, kelas: "XI-3" },
      { nis: "8483", name: "NESSA ACHDIA MAGDALENA TUNGGADEWI", absen: 25, kelas: "XI-3" },
      { nis: "8573", name: "OCTAVIAN AMRULLAH", absen: 26, kelas: "XI-3" },
      { nis: "8513", name: "REIVALDIANO BINTANG MAHARDIKA", absen: 27, kelas: "XI-3" },
      { nis: "8516", name: "REVANO ARDIANSA PUTRA RAMADANI", absen: 28, kelas: "XI-3" },
      { nis: "8519", name: "RIFQI ATHALLAH SYAH", absen: 29, kelas: "XI-3" },
      { nis: "8522", name: "RIZA AKBAR ALMUQSITH", absen: 30, kelas: "XI-3" },
      { nis: "8524", name: "RIZKI ANDI ABDILLAH", absen: 31, kelas: "XI-3" },
      { nis: "8530", name: "SALSA BIEANKA FEBITAMA", absen: 32, kelas: "XI-3" },
      { nis: "8544", name: "TIARA VIONA VIRDAUS", absen: 33, kelas: "XI-3" },
      { nis: "8559", name: "YOSSI AMRU AT-TAUFIK", absen: 34, kelas: "XI-3" },
      { nis: "8562", name: "ZALFA NAIDIA NATASYA", absen: 35, kelas: "XI-3" },
      { nis: "8576", name: "ZASKIA FAIDA AZMI", absen: 36, kelas: "XI-3" },
      
      // Kelas XI-4
      { nis: "8258", name: "ACHMAD FAUZAN DWI GHAZALAH", absen: 1, kelas: "XI-4" },
      { nis: "8262", name: "ADINDA LAILATUZ ZUHRO", absen: 2, kelas: "XI-4" },
      { nis: "8268", name: "AHMAD ELMAN NAFI GUNARTO", absen: 3, kelas: "XI-4" },
      { nis: "8292", name: "ANGGA RIZKY PUTRA SETIAWAN", absen: 4, kelas: "XI-4" },
      { nis: "8301", name: "ARKA DAEGAL ATMA JAYA", absen: 5, kelas: "XI-4" },
      { nis: "8313", name: "AZIZ AHMAD MUDHAKAR", absen: 6, kelas: "XI-4" },
      { nis: "8314", name: "AZLAN RIZQI FEBRIANSYAH", absen: 7, kelas: "XI-4" },
      { nis: "8319", name: "BIANCHA VALENCIA ARIFIZANTY.P", absen: 8, kelas: "XI-4" },
      { nis: "8325", name: "CATRIN AYU MAHESYA", absen: 9, kelas: "XI-4" },
      { nis: "8326", name: "CHALLYSTA ZABANIYAH HOSHI SUSISCO", absen: 10, kelas: "XI-4" },
      { nis: "8327", name: "CHAREN VERONICA KUSUMA", absen: 11, kelas: "XI-4" },
      { nis: "8334", name: "DAHANA SAIKATZU ALBARIZY", absen: 12, kelas: "XI-4" },
      { nis: "8337", name: "DAVIN DWI DARMA", absen: 13, kelas: "XI-4" },
      { nis: "8341", name: "DEVANDIO RIDHO AL KHAFIDZ", absen: 14, kelas: "XI-4" },
      { nis: "8352", name: "ELFITRI SUGI PRIHATI", absen: 15, kelas: "XI-4" },
      { nis: "8381", name: "ISLAUKHA NUZRILIA", absen: 16, kelas: "XI-4" },
      { nis: "8407", name: "M. ABYAZ MAULIDI AL BALAWI", absen: 17, kelas: "XI-4" },
      { nis: "8426", name: "MOCHAMAD NURIL MAHMUDI AL TAZAM BILLAH", absen: 18, kelas: "XI-4" },
      { nis: "8429", name: "MOCHAMMAD IBNU AHLUL A'FA", absen: 19, kelas: "XI-4" },
      { nis: "8435", name: "MUHAMAD SYIAM SEPTIAN SYAH", absen: 20, kelas: "XI-4" },
      { nis: "8444", name: "MUHAMMAD FACHRI AR RASYID", absen: 21, kelas: "XI-4" },
      { nis: "8447", name: "MUHAMMAD FATHIR AFZA ANWAR", absen: 22, kelas: "XI-4" },
      { nis: "8452", name: "MUHAMMAD IRFAN", absen: 23, kelas: "XI-4" },
      { nis: "8455", name: "MUHAMMAD RAGAN ENGGRIYANG", absen: 24, kelas: "XI-4" },
      { nis: "8456", name: "MUHAMMAD RIFKY ARIFUDIN", absen: 25, kelas: "XI-4" },
      { nis: "8471", name: "NAJWA ANINDYA BILQIS RIZKIYUDIN", absen: 26, kelas: "XI-4" },
      { nis: "8477", name: "NAYAKA MAULANA AZKA SYARIF", absen: 27, kelas: "XI-4" },
      { nis: "8485", name: "NIKMA FATIHAH OCEAN HANANI", absen: 28, kelas: "XI-4" },
      { nis: "8493", name: "NURUS SA'IIDATUL HAQIQI", absen: 29, kelas: "XI-4" },
      { nis: "8502", name: "RAFAEL ANGGORO", absen: 30, kelas: "XI-4" },
      { nis: "8505", name: "RAHARDIAN PUTRA RAYA ALBANI", absen: 31, kelas: "XI-4" },
      { nis: "8509", name: "RASYA ISLAMI HEPPY PRATAMA", absen: 32, kelas: "XI-4" },
      { nis: "8517", name: "REZA TANGGUH SAGARA", absen: 33, kelas: "XI-4" },
      { nis: "8534", name: "SEVILLA MAHARANI", absen: 34, kelas: "XI-4" },
      { nis: "8548", name: "VANIA EKA AMANDA PUTRI", absen: 35, kelas: "XI-4" },
      { nis: "8553", name: "WHISNU ADI PRASETYO", absen: 36, kelas: "XI-4" },
      
      // Kelas XI-5
      { nis: "8267", name: "AHMAD DAFFA WIJOYO", absen: 1, kelas: "XI-5" },
      { nis: "8277", name: "ALFA SALMA FARIKHA", absen: 2, kelas: "XI-5" },
      { nis: "8282", name: "ALIF SETIAWAN", absen: 3, kelas: "XI-5" },
      { nis: "8289", name: "ANA FITRIATUL WAKHIDAH", absen: 4, kelas: "XI-5" },
      { nis: "8308", name: "AURA SINTA MARGARETA", absen: 5, kelas: "XI-5" },
      { nis: "8312", name: "AZINDA LINTANG ANA AZ-ZAHRA", absen: 6, kelas: "XI-5" },
      { nis: "8332", name: "CITRA SOFIA RAMADANI", absen: 7, kelas: "XI-5" },
      { nis: "8569", name: "DAFFA AMRULLOH UTOMO", absen: 8, kelas: "XI-5" },
      { nis: "8335", name: "DANIS RAYHAN NUR ABIDIN", absen: 9, kelas: "XI-5" },
      { nis: "8348", name: "DONI DWI HANDIKA", absen: 10, kelas: "XI-5" },
      { nis: "8351", name: "EKA LENI OKTAVIANA", absen: 11, kelas: "XI-5" },
      { nis: "8359", name: "FAIRA RIZKA ELYSIA", absen: 12, kelas: "XI-5" },
      { nis: "8361", name: "FAKHRY DWI JULIANMA", absen: 13, kelas: "XI-5" },
      { nis: "8367", name: "FERA ANGGRAINI", absen: 14, kelas: "XI-5" },
      { nis: "8370", name: "FIOLA RAMADHANIE SHINDU", absen: 15, kelas: "XI-5" },
      { nis: "8379", name: "IMELDA KHARISMA PUTRI", absen: 16, kelas: "XI-5" },
      { nis: "8396", name: "KHANZA CALLISTA AL AZMI", absen: 17, kelas: "XI-5" },
      { nis: "8398", name: "KIRANI DZIL IZZATI", absen: 18, kelas: "XI-5" },
      { nis: "8418", name: "MAWADDAH FATIMATUZZAHRA", absen: 19, kelas: "XI-5" },
      { nis: "8420", name: "MEI SHELLA YOLANDA PUTRI", absen: 20, kelas: "XI-5" },
      { nis: "8424", name: "MITA AULIA", absen: 21, kelas: "XI-5" },
      { nis: "8427", name: "MOCHAMAD TITO PRASETYO", absen: 22, kelas: "XI-5" },
      { nis: "8445", name: "MUHAMMAD FAHRI AZHAR", absen: 23, kelas: "XI-5" },
      { nis: "8451", name: "MUHAMMAD ILHAM FIRMANSYAH", absen: 24, kelas: "XI-5" },
      { nis: "8466", name: "NABILA AYU SALMA", absen: 25, kelas: "XI-5" },
      { nis: "8467", name: "NADIA IMRO'ATUL MUFIDA", absen: 26, kelas: "XI-5" },
      { nis: "8478", name: "NAYLA IQLIMATUL KHAMIDA", absen: 27, kelas: "XI-5" },
      { nis: "8480", name: "NAZILA AZWA SAVIRA", absen: 28, kelas: "XI-5" },
      { nis: "8481", name: "NELY ENJELITA", absen: 29, kelas: "XI-5" },
      { nis: "8487", name: "NIROH NUR AL FINA", absen: 30, kelas: "XI-5" },
      { nis: "8488", name: "NOVIA MAYSAROH", absen: 31, kelas: "XI-5" },
      { nis: "8497", name: "PUTRI AYU MARDIYAH", absen: 32, kelas: "XI-5" },
      { nis: "8503", name: "RAFAEL AURELIO WIDYA PUTRA", absen: 33, kelas: "XI-5" },
      { nis: "8511", name: "REHAN ARYA PRATAMA", absen: 34, kelas: "XI-5" },
      { nis: "8531", name: "SALWA KAYLA PUTRI", absen: 35, kelas: "XI-5" },
      { nis: "8557", name: "YASMIN KHOTFI ROSIDA MUKTI", absen: 36, kelas: "XI-5" }];